#!/bin/bash

token=$(ssh frodo 'sudo cat /var/lib/rancher/k3s/server/node-token')

if [ -z "$token" ]; then
    echo 'Could not retrieve token from frodo'
    exit 1
fi

for hobbit in samwise meriadoc peregrin; do 

    echo "loading $hobbit"
    wait_cycle_time=5
    max_wait_cycles=20
    wait_cycle=0

    ssh $hobbit "export K3S_KUBECONFIG_MODE='644'
    export K3S_URL='https://192.168.1.51:6443'
    export K3S_TOKEN='$token'
    curl -sfL https://get.k3s.io | sh -"

    while true; do
        status=$(ssh $hobbit 'sudo systemctl status k3s-agent' | grep -E '^\s+Active')
        
        if [[ "$status" =~ "active (running)" ]]; then
            break
        fi

        echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ"): $status"
        wait_cycle=$(($wait_cycle+1))

        if [ $wait_cycle -ge $max_wait_cycles ]; then
            echo 'Max wait time exceeded - aborting cluster standup'
            exit 1
        fi

        sleep $wait_cycle_time
    done

    echo "Worker node $hobbit create is successful"
done

echo $token

